
remains-items: # предметы, которые ставятся на голову стенда (трупа)
  # если включен рандом, то на труп будет вешаться случайный предмет
  # если же выключен, то всегда берётся ТОЛЬКО первый предмет из списка
  random: true
  items:
    default: # предмет, который будет ставится на стенд, если 'random: false'
      material: DIAMOND
      custom-model-data: 1488
    golden:
      material: GOLD_INGOT
      custom-model-data: 6767

inventory:
  size: 45 # размер инвентаря трупа
  title: "&0Труп игрока {player-name}" # заголовок инвентаря
  random: true # раскидывать ли предметы по случайным слотам инвентаря