
remains-items: # предметы, которые ставятся на голову стенда (трупа)
  # если включен рандом, то на труп будет вешаться случайный предмет
  # если же выключен, то всегда берётся ТОЛЬКО первый предмет из списка
  random: true
  items:
    default: # предмет, который будет ставится на стенд, если 'random: false'
      material: DIAMOND
      custom-model-data: 1488
    golden:
      material: GOLD_INGOT
      custom-model-data: 6767

inventory:
  size: 45 # размер инвентаря трупа
  title-remain: "&0Труп игрока {player-name}" # заголовок инвентаря трупа
  title-sleeper: "&0Слиппер игрока {player-name}" # заголовок инвентаря слиппера
  random: true # раскидывать ли предметы по случайным слотам инвентаря

cleaning-settings:
  remains:
    isTimer: true
    timer: 120
  sleeper:
    isTimer: true
    timer: 120

stand-settings:
  gravity: true
  position:
    x: 0.0
    y: 0.0
    z: 0.0

different-settings:
  debug: true # подробное логирование
  db-save-delay: 60 # частота вызова сохранения базы данных (в секундах)
  data-save-delay: 60 # частота вызова сохранения uuid трупов в uuids.json (в секундах)
